core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.signin, name='login'),
    path('signup/', views.signup, name='signup'),
    path('signout/', views.signout, name='signout')
]

pbj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('', include('core.urls')),
    path('inventory/', include('inventory.urls')),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    return render(request, 'core/index.html')

def signin(request):
    if request.method == 'POST':
        username = request.POST['username'].title()
        password = request.POST['password']

        if not username or not password:
            return render(request, 'core/login.html', {
                'fail': 'Username or password not found.'
            })
        
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
            
        
        return render(request, 'core/login.html', {
                'fail': 'Username or password not found.'
            })
        
    return render(request, 'core/login.html')

def signup(request):
    if request.method == 'POST':
        username = request.POST['username'].title()
        email = request.POST['email']
        password = request.POST['password']
        
        if not username or not email or not password:
            return render(request, 'core/signup.html', {
                'fail': 'Need to fill out everything.'
            })
        
        if User.objects.filter(username=username).exists():
            return render(request, 'core/signup.html', {
                'fail': 'Username already taken.'
            })
        
        user = User.objects.create_user(username, email, password)
        user.save()
        return render(request, 'core/login.html', {
                'success': 'Successfully signed up.'
            })


    return render(request, 'core/signup.html')


@login_required
def signout(request):
    logout(request)
    return redirect('/')

core/templates/core/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en" >
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    {% tailwind_css %}
</head>
<body class="p-0 m-0 bg-zinc-100 text-zinc-900 dark:bg-zinc-900 dark:text-zinc-100 transition ease-in-out">
    {% if user.is_authenticated %}
        
        <!--Home if logged in-->
                    
            <header class="relative w-11/12 lg:w-3/4 h-20 mx-auto z-10 ">

                <!--Mobile-->
                <div class="w-full h-full md:invisible md:hidden">
                    <div class="flex flex-row text-center h-full space-x-4">
                        
                        <div class="my-auto flex">
                            <a href="{% url 'core:index' %}" class="text-lg sm:text-2xl font-semibold my-auto">PBJ.</a>
                        </div>

                        <form action="" class="my-auto flex-1 flex">
                            <input type="text" placeholder="Search part" autocomplete="off" class="w-full pl-5 py-3 rounded-lg shadow-sm outline-none bg-zinc-300 dark:bg-zinc-700 placeholder:text-zinc-500 border-transparent focus:border-transparent focus:ring-0 focus:text-white focus:bg-zinc-600 focus:placeholder:text-white dark:focus:placeholder:text-zinc-900 dark:focus:bg-zinc-200 dark:focus:text-zinc-900 focus:rounded-full">
                            <button class="-ml-8">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
                                    <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                                </svg>
                            </button>
                        </form>

                        <div class="m-auto flex">
                            <a href="" class="font-semibold m-auto">drop</a>
                        </div>
                    </div>
                </div>

                <!--Other Devices-->
                <div class="w-full h-full hidden md:visible md:flex space-x-2.5">

                    <div class="flex">
                        <a href="{% url 'core:index' %}" class="text-2xl font-semibold my-auto">PBJ.</a>
                    </div>
                    
                    <form action="" class="my-auto flex-1 flex">
                        <input type="text" placeholder="Search part" autocomplete="off" class="w-full pl-5 py-3 rounded-lg shadow-sm outline-none bg-zinc-300 dark:bg-zinc-700 placeholder:text-zinc-500 border-transparent focus:border-transparent focus:ring-0 focus:text-white focus:bg-zinc-600 focus:placeholder:text-white dark:focus:placeholder:text-zinc-900 dark:focus:bg-zinc-200 dark:focus:text-zinc-900 focus:rounded-full">
                        <button class="-ml-8">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
                                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                            </svg>
                        </button>
                    </form>

                    <div class="my-auto flex space-x-2 text-sm font-semibold">
                        
                        <button id="theme-toggle" class="py-4 px-4 bg-zinc-900 text-zinc-100 dark:bg-zinc-100 dark:text-zinc-900 rounded-lg hover:bg-zinc-800 dark:hover:bg-zinc-300">
                            <span id="light-mode" class="hidden">Light Mode</span>
                            <span id="dark-mode" class="hidden">Dark Mode</span>
                        </button>
                        <a href="{% url 'core:signout' %}" class="my-auto px-4 rounded-lg">
                            <div class="relative inline-flex items-center justify-center h-12 w-12 overflow-hidden bg-zinc-900 dark:bg-zinc-100 text-zinc-100 dark:text-zinc-900 rounded-full">
                                <span class="font-medium">{{ request.user.username }}</span>
                            </div>
                        </a>
                        <a href="" class="py-4 px-4 rounded-lg hover:bg-zinc-900 hover:text-zinc-100 dark:hover:bg-zinc-100 dark:hover:text-zinc-900 ">Cart</a>
                    </div>

                </div>

            </header>

        {% block body %}
        {% endblock %}

        <footer class="relative w-11/12 lg:w-3/4 h-20 mx-auto">
            <div class="h-full flex m-auto justify-end">
                <div class="my-auto font-semibold">Created By PoopyButtJ</div>
            </div>
        </footer>

                
    {% else %}

    <!--Home if not logged in-->
    <div class="min-h-screen bg-zinc-100 text-zinc-900 dark:bg-zinc-900 dark:text-zinc-100 overflow-hidden">

        <header class="h-20 absolute top-0 left-0 right-0 w-11/12 lg:w-3/4 mx-auto z-10">
            <div class="w-full h-full flex flex-row justify-between mx-auto">
                <div class="my-auto justify-start">
                    <a href="{% url 'core:index' %}" class="text-2xl xxl:text-3xl font-semibold">PBJ.</a>
                </div>
                <div class="my-auto flex sm:space-x-6 justify-end">
                    <a href="{% url 'core:login' %}" class="py-3 px-4 rounded-lg hover:bg-zinc-900 hover:text-white dark:hover:bg-zinc-100 dark:hover:text-zinc-900">Sign In</a>
                    <a href="{% url 'core:signup' %}" class="py-3 px-4 rounded-lg hover:bg-zinc-900 hover:text-white dark:hover:bg-zinc-100 dark:hover:text-zinc-900">Sign Up</a>
                </div>
            </div>
        </header>
        {% block nobody %}{% endblock %}

    </div>
    {% endif %}

    <script>

        if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
            document.documentElement.classList.add('dark');
        } else {
            document.documentElement.classList.remove('dark')
        }
        
        var themeToggleDarkIcon = document.getElementById('dark-mode');
        var themeToggleLightIcon = document.getElementById('light-mode');

        // Change the icons inside the button based on previous settings
        if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
            themeToggleLightIcon.classList.remove('hidden');
        } else {
            themeToggleDarkIcon.classList.remove('hidden');
        }


        var themeToggleBtn = document.getElementById('theme-toggle');

        themeToggleBtn.addEventListener('click', function() {

            // toggle icons inside button
            themeToggleDarkIcon.classList.toggle('hidden');
            themeToggleLightIcon.classList.toggle('hidden');

            // if set via local storage previously
            if (localStorage.getItem('color-theme')) {
                if (localStorage.getItem('color-theme') === 'light') {
                    document.documentElement.classList.add('dark');
                    localStorage.setItem('color-theme', 'dark');
                } else {
                    document.documentElement.classList.remove('dark');
                    localStorage.setItem('color-theme', 'light');
                }

            // if NOT set via local storage previously
            } else {
                if (document.documentElement.classList.contains('dark')) {
                    document.documentElement.classList.remove('dark');
                    localStorage.setItem('color-theme', 'light');
                } else {
                    document.documentElement.classList.add('dark');
                    localStorage.setItem('color-theme', 'dark');
                }
            }
            
        });

    </script>
</body>
</html>

core/templates/core/login.html
{% extends 'core/base.html' %}
{% block title %}Login{% endblock %}
{% block nobody %}
<main id="main" class="relative flex h-screen w-11/12 xl:w-10/12 mx-auto">
    
    <form action="{% url 'core:login' %}" method="post" class="m-auto bg-white p-12 sm:p-16 max-w-md shadow-md rounded-lg dark:text-zinc-900">
        {% csrf_token %}
        <label for="name" class="text-sm font-bold">Username</label>
        <input type="text" name="username" class="relative block my-3 py-2 pl-4 rounded " autofocus>
        <label for="password" class="text-sm font-bold">Password</label>
        <input type="password" name="password" class="relative block my-3 py-2 pl-4 rounded ">
        <button type="submit" class="my-3 w-full py-3 bg-zinc-900 text-white rounded hover:rounded-full transition ease-in-out delay-150">Sign in</button>
        {% if success %}
        <p class="text-xs font-bold text-emerald-600"> {{ success }} </p>
        {% elif fail %}
        <p class="text-xs font-bold text-rose-600"> {{ fail }} </p>
        {% endif %}
    </form>

</main>

{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}
{% block title %}Sign Up{% endblock %}
{% block nobody %}
<main id="main" class="relative flex h-screen w-11/12 xl:w-10/12 mx-auto">
    
    <form action="{% url 'core:signup' %}" method="post" class="m-auto bg-white p-12 sm:p-16 max-w-md shadow-md rounded-lg dark:text-zinc-900">
        {% csrf_token %}
        <label for="username" class="text-sm font-bold">Username</label>
        <input type="text" name="username" class="relative block my-1 sm:my-3 py-2 pl-4 rounded focus:outline-none" autofocus>
        <label for="email" class="text-sm font-bold">Email</label>
        <input type="text" name="email" class="relative block my-1 sm:my-3 py-2 pl-4 rounded focus:outline-none" autofocus>
        <label for="password" class="text-sm font-bold">Password</label>
        <input type="password" name="password" class="relative block my-1 sm:my-3 py-2 pl-4 rounded focus:outline-none">
        <button type="submit" class="my-3 w-full py-3 bg-zinc-900 text-white rounded hover:rounded-full transition ease-in-out">Sign up</button>
        {% if fail %}
        <p class="text-xs font-bold text-rose-600"> {{ fail }} </p>
        {% endif %}
    </form>

</main>
{% endblock %}