inventory/urls.py
from django.urls import path

from . import views

app_name = 'inventory'

urlpatterns = [
    path('', views.index, name='index'),
    path('logs/', views.logs, name='logs'),
    path('browse/', views.browse, name='browse'),
]

pbj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('', include('core.urls')),
    path('inventory/', include('inventory.urls')),
]

inventory/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    category =  models.CharField(max_length=64)

    def __str__(self):
        return self.category
    

class Part(models.Model):
    name = models.CharField(max_length=100, unique=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    description = models.CharField(max_length=100)
    price = models.FloatField()
    date = models.DateField()

    @property
    def usd(self):
        return f'${self.price:,.2f}'

    def __str__(self):
        return f'({self.category}) {self.name} {self.usd}'
    

class Inventory(models.Model):
    part = models.ForeignKey(Part, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField()

    @property
    def total(self):
        value = self.part.price * self.quantity
        return f'${value:,.2f}'
    
    def __str__(self):
        return f'({self.part.category}) {self.part.name} Qty: {self.quantity} Price: {self.part.usd} Total: {self.total}'
    

class Log(models.Model):
    part = models.ForeignKey(Part, on_delete=models.SET_NULL, null=True)
    method = models.CharField(max_length=40)
    quantity = models.IntegerField()
    user = models.CharField(max_length=40)
    date = models.DateTimeField()

    @property
    def total(self):
        value = self.part.price * self.quantity
        return f'${value:,.2f}'
    
    def __str__(self):
        return f'({self.part.category}) {self.part.name} {self.method} Qty: {self.quantity} Total: {self.total} User: {self.user} Date: {self.date}'

inventory/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import Part, Category, Inventory, Log
import datetime

# Create your views here.

@login_required
def index(request):

    # Add inventory
    if request.method == 'POST' and 'add_form' in request.POST:
        part = request.POST['part'].title()\
        
        # Check that quantity is valid float number
        try:
            quantity = int(request.POST['quantity'])
        except ValueError:
            return render(request, 'inventory/index.html', {
                'fail': 'Quantity not of correct value.'
            })
        
        # Check that user filled out everything
        if not part or not quantity:
            return render(request, 'inventory/index.html', {
                'fail': 'Need to fill out both part and quanitity.'
            })
        
        # Check if part exists
        try:
            part_data = Part.objects.get(name=part)
        except:
            return render(request, 'inventory/index.html', {
                'fail': 'Part not found'
            })
        
        # Check if part already in inventory to update quantity if not create it
        try:
            inventory = Inventory.objects.get(part=part_data)
            inventory.quantity += quantity
            inventory.save()
        except:
            Inventory.objects.create(
                part=part_data,
                quantity = quantity,
            )
        
        # Create log for update of inventory
        date = datetime.datetime.now()
        Log.objects.create(
            part = part_data,
            method = 'Add',
            quantity = quantity,
            user = request.user.username,
            date = date,
        )

        return render(request, 'inventory/index.html', {
            'success': f'Successfully updated inventory for {part_data.name}'
        })


    # Edit inventory
    if request.method == 'POST' and 'edit_form' in request.POST:
        part = request.POST['part'].title()
        update_name = request.POST['update_name'].title()
        update_category = request.POST['update_category'].title()
        update_quantity = request.POST['update_quantity']
        update_price = request.POST['update_price']

        if not part:
            return render(request, 'inventory/index.html', {
                'fail': 'Must provide a part name.'
            })
        
        # Check that part exists in inventory
        try:
            part_data = Part.objects.get(name=part)
            inventory_data = Inventory.objects.get(part=part_data)
            # Get old data to display changes made
            old_inventory = Inventory.objects.get(part=part_data)
            old_category = part_data.category
            old_price = part_data.usd
            old_total = old_inventory.total
        except:
            return render(request, 'inventory/index.html', {
                'fail': 'Part not found in inventory.'
            })
        

        # Get category data if exist else create new category
        try:
            category_data = Category.objects.get(category=update_category)
        except:
            category_data = Category.objects.create(category=update_category)
        
        
        # Change values of part if information was provided
        if update_name:
            part_data.name = update_name

        if update_category:
            part_data.category = category_data
        
        if update_price:
            try:
                update_price = float(update_price)
            except ValueError:
                return render(request, 'inventory/index.html', {
                    'fail': 'Price not a valid value.'
                })
            part_data.price = update_price

        if update_quantity:
            try:
                update_quantity = int(update_quantity)
            except ValueError:
                return render(request, 'inventory/index.html', {
                    'fail': 'Quantity not a valid value.'
                })
            inventory_data.quantity = update_quantity


        # Save after all changes have been made
        part_data.save()
        inventory_data.save()

        # Get data about the updated part inorder to log info about the change else use provided part
        if update_name:
            part_to_log = Part.objects.get(name=update_name)
        else:
            part_to_log = Part.objects.get(name=part)

        part_inventory = Inventory.objects.get(part=part_to_log)

        date = datetime.datetime.now()
        Log.objects.create(
            part = part_to_log,
            method = 'Edit',
            quantity = part_inventory.quantity,
            user = request.user.username,
            date = date,
        )

        return render(request, 'inventory/index.html', {
            'success': f'Succesfully changed  to {part_inventory}',
            'previous': f'from ({old_category}) {part} Qty: {old_inventory.quantity} Price: {old_price} Total: {old_total}'
        })



    # Create inventory
    if request.method == 'POST' and 'create_form' in request.POST:
        part = request.POST['part'].title()
        category = request.POST['category'].title()
        description = request.POST['description'].title()
        price = request.POST['price']
        if not part or not category or not description or not price:
            return render(request, 'inventory/index.html', {
                'fail': 'Need to fill out everything.'
            })

        try:
            price = float(price)
        except ValueError:
            return render(request, 'inventory/index.html', {
                'fail': 'price not of correct value.'
            })

        date = datetime.date.today()

        if Part.objects.filter(name=part).exists():
            return render(request, 'inventory/index.html', {
                'fail': 'Part with name already exists.'
            })
        

        category_data = Category.objects.filter(category=category)
        if category_data.exists():
            Part.objects.create(
                name = part,
                category = category_data.first(),
                description = description,
                price = price,
                date = date,
            )
        else:
            category_data = Category.objects.create(category=category)
            Part.objects.create(
                name = part,
                category = category_data,
                description = description,
                price = price,
                date = date,
            )

        return render(request, 'inventory/index.html', {
            'success': 'Sucessfully created part.'
        })
        
        
    return render(request, 'inventory/index.html')


@login_required
def logs(request):
    date = datetime.date.today()
    today = Log.objects.filter(date__contains=date).order_by('-date')
    yesterday = Log.objects.filter(date__contains=date-datetime.timedelta(days=1)).order_by('-date')
    return render(request, 'inventory/logs.html', {
        'today': today,
        'yesterday': yesterday,
    })
    

@login_required
def browse(request):
    inventory = Inventory.objects.all()
    categories = set()
    for part in inventory:
        categories.add(part.part.category)

    return render(request, 'inventory/browse.html', {
        'inventory': inventory,
        'categories': categories
    })

inventory/templates/inventory/browse.html
{% extends 'core/base.html' %}
{% block title %}Browse{% endblock %}
{% block body %}
<main>
    <div class="w-11/12 lg:w-3/4 h-60 mx-auto flex">
        <div class="m-auto text-center font-semibold">
            <div class="text-7xl mb-4">Browse Inventory</div>
        </div>
    </div>

    <div class="w-full py-20 bg-white dark:bg-black">
        <div class="w-11/12 lg:w-3/4 2xl:w-7/12 mx-auto flex gap-6">
            <div class="w-1/6 h-96 bg-zinc-200 dark:bg-zinc-900 rounded-2xl">
                <div class="px-4 py-4 leading-relaxed">
                    <div class="font-semibold text-xl">Filter by category</div>
                    
                    {% for category in categories %}
                    <div><a href="">{{ category }}</a></div>
                    {% endfor %}
                </div>
                
            </div>
            <div class="w-4/5 grid grid-cols-3 gap-3">
                {% for part in inventory %}
                <div class="h-72 bg-zinc-200 dark:bg-zinc-900 rounded-2xl px-6 py-10">
                    <div class="h-1/6 flex"><div class="block text-3xl font-bold my-auto"> {{ part.part.name }} </div></div>
                    <div class="h-2/3 font-semibold text-md flex">
                        <div class="my-auto">
                            <div> Category: {{ part.part.category }} </div>
                            <div> Description: {{ part.part.description }} </div>
                            <div> Price: {{ part.part.usd }} </div>
                            <div> In stock: {{ part.quantity }} </div>
                        </div>
                    </div>
                    <div class="h-1/6">
                        <input type="number" class="w-20 py-3 text-zinc-900" value="1" min="1">
                        <button class="px-4 py-3 text-zinc-100 dark:text-zinc-900 bg-zinc-900 dark:bg-zinc-100 hover:rounded-full font-semibold">Add to bag</button>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</main>
{% endblock %}

inventory/templates/inventory/index.html
{% extends 'core/base.html' %}
{% block title %}Inventory{% endblock %}
{% block body %}
<main>
    <div class="w-11/12 lg:w-3/4 h-60 mx-auto flex">
        <div class="m-auto  text-center">
            <div class="text-7xl font-semibold mb-4">Manage inventory</div>
        </div>
    </div>

    <div class="w-full py-20 bg-white dark:bg-black">
        
        {% if fail %}
        <div class="w-full h-12 text-xl text-rose-500 text-center font-semibold"> {{ fail }} </div>
        {% elif success %}
        <div class="w-full h-12 text-xl text-emerald-600 text-center font-semibold"> {{ success }} </div>
        <div class="w-full h-12 text-xl text-rose-500 text-center font-semibold"> {{ previous }} </div>
        {% endif %}
        <div class="w-11/12 lg:w-3/4 2xl:w-1/2 h-[700px] m-auto block">
            
            <!--FORMS-->
            <!--Add Form-->
            
            <div id="addForm" class="hidden absolute h-[700px] w-11/12 lg:w-3/4 2xl:w-1/2 bg-zinc-300 dark:bg-zinc-900 opacity-0 animate-show">
                <div class="py-2 px-2"><button class="close-add text-3xl">&times;</button></div>
                <div class="relative flex h-full w-full">
                    <form action="{% url 'inventory:index' %}" class="relative -top-20 m-auto p-20 " method="post">
                        {% csrf_token %}
                        <div class="text-4xl font-semibold mb-10 uppercase">Add Inventory</div>
                        <div class="w-full mb-2">
                            <label for="part" class="text-sm">Part name</label>
                            <input type="text" name="part" class="block w-full text-zinc-900 pl-2" autofocus autocomplete="off" placeholder="Name">
                        </div>
                        <div class="w-full mb-5">
                            <label for="quantity" class="text-sm">Quantity</label>
                            <input type="text" name="quantity" class="block w-full text-zinc-900 pl-2" autocomplete="off" placeholder="Quantity">
                        </div>
                        <div class="text-center w-full">
                            <input type="submit" class="py-3 px-5  cursor-pointer shadow-sm bg-white dark:bg-black hover:scale-105 text-center w-full" name="add_form">
                        </div>
                    </form>
                </div>
            </div>
            <!--Edit Form-->
            <div id="editForm" class="hidden absolute h-[700px] w-11/12 lg:w-3/4 2xl:w-1/2 bg-zinc-300 dark:bg-zinc-900 opacity-0 animate-show">
                <div class="py-2 px-2"><button class="close-edit text-3xl">&times;</button></div>
                <div class="relative flex h-full w-full">
                    <form action="{% url 'inventory:index' %}" method="post" class="relative -top-20 m-auto p-20 ">
                        {% csrf_token %}
                        <div class="text-4xl font-semibold mb-10 uppercase">Edit Inventory</div>
                        <div class="w-full mb-2">
                            <label for="part" class="text-sm font-medium">Part name</label>
                            <input type="text" name="part" class="block w-full text-zinc-900 pl-2" autofocus autocomplete="off">
                        </div>
                        <div class="w-full mb-2 text-center capitalize">
                            <input id="check_name" type="checkbox" name="name" id="" class="w-4 h-4 rounded" data-input="updateName">
                            <label for="check_name" class="" placeholder="Name">name</label>
                            <input id="check_category" type="checkbox" name="category" id="" class="w-4 h-4 rounded" data-input="updateCategory">
                            <label for="check_category" class="" placeholder="Category">category</label>
                            <input id="check_quantity" type="checkbox" name="quantity" id="" class="w-4 h-4 rounded" data-input="updateQuantity">
                            <label for="check_quantity" class="" placeholder="Quantity">quantity</label>
                            <input id="check_price" type="checkbox" name="price" id="" class="w-4 h-4 rounded" data-input="updatePrice">
                            <label for="check_price" class="" placeholder="Price">price</label>
                            
                        </div>
                        <div id="updateName" class="hidden w-full mb-3">
                            <label for="update_name" class="text-sm font-medium">Update Part name</label>
                            <input type="text" name="update_name" class="block w-full text-zinc-900 pl-2" autofocus autocomplete="off" placeholder="Name">
                        </div>
                        <div id="updateCategory" class="hidden w-full mb-3">
                            <label for="update_category" class="text-sm font-medium">Update Category</label>
                            <input type="text" name="update_category" class="block w-full text-zinc-900 pl-2" autofocus autocomplete="off" placeholder="Category">
                        </div>
                        <div id="updateQuantity" class="hidden w-full mb-3">
                            <label for="update_quantity" class="text-sm font-medium">Update Quantity</label>
                            <input type="text" name="update_quantity" class="block w-full text-zinc-900 pl-2" autofocus autocomplete="off" placeholder="Quantity">
                        </div>
                        <div id="updatePrice" class="hidden w-full mb-3">
                            <label for="update_price" class="text-sm font-medium">Update Price</label>
                            <input type="text" name="update_price" class="block w-full text-zinc-900 pl-2" autofocus autocomplete="off" placeholder="Price">
                        </div>
                        
                        
                        <div class="text-center w-full py-2">
                            <input type="submit" class="py-3 px-5  cursor-pointer shadow-sm bg-white dark:bg-black hover:scale-105 text-center w-full" name="edit_form">
                        </div>
                        
                    </form>
                </div>
            </div>

            <!--Create Form-->
            <div id="createForm" class="hidden absolute h-[700px] w-11/12 lg:w-3/4 2xl:w-1/2 bg-zinc-300 dark:bg-zinc-900 opacity-0 animate-show">
                <div class="py-2 px-2"><button class="close-create text-3xl">&times;</button></div>
                <div class="relative flex h-full w-full">
                    <form action="{% url 'inventory:index' %}" method="post" class="relative -top-20 m-auto p-20 ">
                        {% csrf_token %}
                        <div class="text-4xl font-semibold mb-10 uppercase">Create Inventory</div>
                        <div class="w-full mb-2">
                            <label for="part" class="text-sm">Part name</label>
                            <input type="text" name="part" class="block w-full text-zinc-900 pl-2" autofocus autocomplete="off" placeholder="Name">
                        </div>
                        <div class="w-full mb-5">
                            <label for="category" class="text-sm">Category</label>
                            <input type="text" name="category" class="block w-full text-zinc-900 pl-2" autocomplete="off" placeholder="Category">
                        </div>
                        <div class="w-full mb-5">
                            <label for="description" class="text-sm">Description</label>
                            <input type="text" name="description" class="block w-full text-zinc-900 pl-2" autocomplete="off" placeholder="Description">
                        </div>
                        <div class="w-full mb-5">
                            <label for="price" class="text-sm">Price</label>
                            <input type="text" name="price" class="block w-full text-zinc-900 pl-2" autocomplete="off" placeholder="Price">
                        </div>
                        <div class="text-center w-full">
                            <input type="submit" class="py-3 px-5  cursor-pointer shadow-sm bg-white dark:bg-black hover:scale-105 text-center w-full" name="create_form">
                        </div>
                        
                    </form>
                </div>
            </div>


            <!--Home grid-->
            <div class="grid grid-cols-1 grid-rows-3 lg:grid-cols-2 lg:grid-rows-2 gap-4 h-full w-full text-center transition ease-in-out">
                <div id="add" class=" bg-zinc-200 hover:bg-zinc-300 dark:bg-zinc-900 dark:hover:bg-zinc-700 rounded-xl shadow-md flex cursor-pointer">
                    <div class="m-auto w-10/12">
                        <div class="text-3xl lg:text-5xl font-semibold mb-3 capitalize">Add inventory</div>
                        <div class="text-sm lg:text-base font-semibold">Increase the quantity of a part.</div>
                    </div>
                </div>
                <div id="edit" class=" bg-zinc-200 hover:bg-zinc-300 dark:bg-zinc-900 dark:hover:bg-zinc-700 rounded-xl shadow-md flex cursor-pointer">
                    <div class="m-auto w-10/12">
                        <div class="text-3xl lg:text-5xl font-semibold mb-3 capitalize">Edit inventory</div>
                        <div class="text-sm lg:text-base font-semibold">Make changes to the values of a part.</div>
                    </div>
                </div>
                <div id="create" class="lg:col-span-2 bg-zinc-200 hover:bg-zinc-300 dark:bg-zinc-900 dark:hover:bg-zinc-700 rounded-xl shadow-md flex cursor-pointer">
                    <div class="m-auto w-10/12">
                        <div class="text-3xl lg:text-5xl font-semibold mb-3 capitalize">Create new Part</div>
                        <div class="text-sm lg:text-base font-semibold">Create an entirely new part to began storing inventory for.</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        // Add form
        const add = document.querySelector('#add');
        const addForm = document.querySelector('#addForm');
        add.addEventListener('click', ()=> {
            addForm.classList.toggle('hidden');
        });

        const closeAdd = document.querySelector('.close-add');
        closeAdd.onclick = ()=> {addForm.classList.toggle('hidden');};
        
        // Edit form
        const edit = document.querySelector('#edit');
        const editForm = document.querySelector('#editForm');
        edit.addEventListener('click', ()=> {
            editForm.classList.toggle('hidden');
        });

        const closeEdit = document.querySelector('.close-edit');
        closeEdit.onclick = ()=> {editForm.classList.toggle('hidden');};


        // Checkbox
        const updateName = document.querySelector('#updateName');
        const updateCategory = document.querySelector('#updateCategory');
        const updateQuantity = document.querySelector('#updateQuantity');
        const updatePrice = document.querySelector('#updatePrice');
        const nameCheckbox = document.querySelector('#check_name');
        const categoryCheckbox = document.querySelector('#check_category');
        const quantityCheckbox = document.querySelector('#check_quantity');
        const priceCheckbox = document.querySelector('#check_price');
        nameCheckbox.addEventListener('change', ()=> {
            if (nameCheckbox.checked) {
                updateName.classList.toggle('hidden');
            } else {
                updateName.classList.add('hidden');
            }
        });
        
        categoryCheckbox.addEventListener('change', ()=> {
            if (categoryCheckbox.checked) {
                updateCategory.classList.toggle('hidden');
            } else {
                updateCategory.classList.add('hidden');
            }
        });

        quantityCheckbox.addEventListener('change', ()=> {
            if (quantityCheckbox.checked) {
                updateQuantity.classList.toggle('hidden');
            } else {
                updateQuantity.classList.add('hidden');
            }
        });

        priceCheckbox.addEventListener('change', ()=> {
            if (priceCheckbox.checked) {
                updatePrice.classList.toggle('hidden');
            } else {
                updatePrice.classList.add('hidden');
            }
        });


        // Create form
        const create = document.querySelector('#create');
        const createForm = document.querySelector('#createForm');
        create.onclick = ()=> {createForm.classList.toggle('hidden')};

        const closeCreate = document.querySelector('.close-create');
        closeCreate.onclick = function() {createForm.classList.toggle('hidden');};
        
    </script>
    
    
</main>
{% endblock %}

inventory/templates/inventory/logs.html
{% extends 'core/base.html' %}
{% block title %}Logs{% endblock %}
{% block body %}
<main>
    <div class="w-11/12 lg:w-3/4 h-60 mx-auto flex">
        <div class="m-auto text-center font-semibold">
            <div class="text-7xl mb-4">Inventory Logs</div>
        </div>
    </div>

    <div class="w-full py-20 bg-white dark:bg-black">
        <div class="w-11/12 lg:w-3/4 mx-auto text-lg font-semibold mb-2">Changes made today:</div>
        <div class="w-11/12 lg:w-3/4 mx-auto shadow-sm dark:shadow-md bg-zinc-100 dark:bg-zinc-900 rounded-2xl overflow-hidden">
            <table class="w-full text-center">
                <thead class="uppercase text-sm bg-zinc-200 dark:bg-zinc-800">
                    <tr>
                        <th scope="col" class="px-6 py-3">Part</th>
                        <th scope="col" class="px-6 py-3">method</th>
                        <th scope="col" class="px-6 py-3">quantity</th>
                        <th scope="col" class="px-6 py-3">total</th>
                        <th scope="col" class="px-6 py-3">user</th>
                        <th scope="col" class="px-6 py-3">date</th>
                    </tr>
                </thead>
                <tbody class=" font-semibold">
                    {% for log in today %}
                    <tr>
                        <th scope="row" class="px-6 py-2"> {{ log.part.name }}</th>
                        <td class="px-6 py-2"> {{ log.method }} </td>
                        <td class="px-6 py-2"> {{ log.quantity }} </td>
                        <td class="px-6 py-2"> {{ log.total }} </td>
                        <td class="px-6 py-2"> {{ log.user }} </td>
                        <td class="px-6 py-2"> {{ log.date }} </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</main>
{% endblock %}